name: Push workflow

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:

  housekeeping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform housekeeping checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source <(curl -sL http://ci.q-ctrl.com)
        ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}        
        ./ci docker run qctrl/python-build:3.7 /scripts/housekeeping.sh

  publish_internally:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish development version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source <(curl -sL http://ci.q-ctrl.com)
        ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
        ./ci docker run qctrl/python-build:3.7 /scripts/publish-dev-version.sh